### ISSUE TITLE
Recommendation use `FetchContent` instead of git module directly

### ISSUE THREAD

**Issue by LecrisUT** [cda-tum/mqt-qcec#302]
```cmake
FetchContent_Declare(mqt-core
            GIT_REPOSITORY https://github.com/cda-tum/mqt-core
            GIT_TAG 1.11.1
            FIND_PACKAGE_ARGS REQUIRED
            )
```
This allows the user to switch between:
- Downloaded dependency `-DFETCHCONTENT_TRY_FIND_PACKAGE_MODE=NEVER`
- System installed (default): remove `REQUIRED` if you wish to have it fallback
- Git submodule `-DFETCHCONTENT_SOURCE_DIR_<uppercaseName>=/path/to/submodule`
- Other implementations: `Find<Package>.cmake`

Note that the full syntax is only available in `Cmake 3.24`, but you can make a simple compatibility: [example](https://github.com/pboettch/json-schema-validator/blob/f4194d7e24e2e2365660ff35b57a7c4e088b27fa/CMakeLists.txt#L85-L103)

Please link upstream to this issue as well

**Comment by burgholzer** [comment]
Many thanks for the suggestion! That seems like a convenient solution.
Would I still keep the `mqt-core` submodule in that kind of setup?

Just out of curiosity: Let's say I want to try a development version of `mqt-core` (no git tag available). In the current setup, that is as easy changing the submodule commit. How would that work with `FetchContent_Declare`?

**Comment by LecrisUT** [comment]
> Would I still keep the `mqt-core` submodule in that kind of setup?

Yes, I do recommend to keep the submodule as well. That would help with offline installations

> Just out of curiosity: Let's say I want to try a development version of mqt-core (no git tag available). In the current setup, that is as easy changing the submodule commit. How would that work with FetchContent_Declare?

My workflow is to declare `-DFETCHCONTENT_SOURCE_DIR_<uppercaseName>=/path/to/submodule` in these cases an point it to my local git repo (not the submodule).

**Comment by burgholzer** [comment]
Given that all of our core tools now rely on `FetchContent` over directly using the submodules, I believe this can be closed for now 🎉 
Thanks @LecrisUT for the suggestion!
