### ISSUE TITLE
🐛 Simulations only work correctly for the first run and check nothing from the second run

### ISSUE THREAD

**Issue by canhminhdo** [cda-tum/mqt-qcec#347]
### Environment information

- OS: Mac 
- C++ compiler: Apple clang version 15.0.0
- mqt.core version: newest

### Description

Each simulation is executed on a TaskManager. However, after completing each simulation, the TaskManager did not reset the iterator to the beginning of quantum operations so that the next simulation could be executed normally. 
Therefore, the iterator remains at the end of quantum operations and nothing is executed for the next simulation. Consequently, the result from the second simulation is always equivalent.

### Expected behavior

After completing each simulation, the TaskManager has to reset the iterator to the beginning of quantum operations.

### How to Reproduce

See the situation by simply checking the equivalence of the following two circuits with simulations
qc1.x(0);
qc2.x(0);

// add a global phase of -1
qc2.z(0);
qc2.x(0);
qc2.z(0);
qc2.x(0);

**Comment by burgholzer** [comment]
Thanks for raising this issue! I can confirm the underlying problem and have absolutely no idea how that has not surfaced earlier in the tests or during actual use.
#348 should fix this.

**Comment by canhminhdo** [comment]
I have been reading and learning mqt-qec source code. It would be very helpful if you could briefly explain the meaning of changing permutation, reducing ancillae, and reducing garbage and why we need it as a post-process for the result.
If you have details of how the development has been done, it would be much better.
Thank you!
