### ISSUE TITLE
Segmentation fault and bus error when running qcec

### ISSUE THREAD

**Issue by ritu-thombre99** [cda-tum/mqt-qcec#424]
### Environment information

OS: MacOS
MQT version: 2.6.0
Compiler: C++

### Description

I'm trying to run a circuit equivalence check for two particular circuits (Steane code).
There are no mid-circuit measurements, and I have
I get 
1. segmentation fault with ```qcec.verify("circ1.qasm", "circ2.qasm", transform_dynamic_circuit=True)```
2. bus error with ```qcec.verify("circ1.qasm", "circ2.qasm")```

Circ1.qasm is an actual code of Steane code circuit
Circ2.qasm is a hardware aware compiled circuit for the following coupling map:
```
 connection=[
        (0, 1),
        (1, 2),
        (2, 3),
        (2, 5),
        (4, 5),
        (5, 6),
        (5, 8),
        (7, 8),
        (8, 9),
        (9, 10),
        (3, 11),
        (7, 12),
        (10, 13),
        (0, 14),
    ],
```
Qubit 13 and 14 on the coupling graph are special, and cannot be used for any gates, only measuring the rest of the qubits.

circ1.qasm:
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[13];
creg c[3];
x q[5];
cx q[0],q[7];
cx q[2],q[7];
cx q[4],q[7];
cx q[6],q[7];
cx q[1],q[8];
cx q[2],q[8];
cx q[5],q[8];
cx q[6],q[8];
cx q[3],q[9];
cx q[4],q[9];
cx q[5],q[9];
cx q[6],q[9];
measure q[7] -> c[0];
measure q[8] -> c[1];
measure q[9] -> c[2];
```

circ2.qasm
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[15];
creg c[3];
cx q[3],q[2];
cx q[7],q[8];
cx q[9],q[8];
cx q[5],q[8];
cx q[5],q[2];
cx q[1],q[2];
cx q[2],q[1];
cx q[1],q[2];
cx q[4],q[5];
cx q[5],q[4];
cx q[4],q[5];
cx q[2],q[5];
cx q[8],q[9];
cx q[9],q[8];
cx q[8],q[9];
cx q[8],q[5];
cx q[3],q[11];
cx q[11],q[3];
cx q[3],q[11];
cx q[2],q[3];
cx q[3],q[2];
cx q[2],q[3];
rx(pi) q[2];
cx q[2],q[5];
cx q[2],q[1];
cx q[2],q[3];
cx q[3],q[2];
cx q[2],q[3];
cx q[3],q[11];
cx q[11],q[3];
cx q[3],q[11];
cx q[7],q[12];
cx q[12],q[7];
cx q[7],q[12];
cx q[7],q[8];
cx q[8],q[7];
cx q[7],q[8];
cx q[7],q[12];
cx q[8],q[9];
cx q[8],q[5];
cx q[5],q[8];
cx q[8],q[5];
cx q[5],q[8];
cx q[2],q[5];
cx q[5],q[2];
cx q[2],q[5];
cx q[2],q[1];
cx q[0],q[1];
cx q[1],q[0];
cx q[0],q[1];
cx q[2],q[5];
cx q[5],q[2];
cx q[2],q[5];
cx q[9],q[10];
cx q[10],q[9];
cx q[9],q[10];
cx q[8],q[9];
cx q[9],q[8];
cx q[8],q[9];
cx q[12],q[7];
cx q[7],q[12];
cx q[7],q[12];
cx q[12],q[7];
cx q[7],q[12];
measure q[13] -> c[0];
measure q[10] -> c[0];
cx q[9],q[10];
cx q[10],q[9];
cx q[9],q[10];
measure q[13] -> c[1];
measure q[10] -> c[1];
measure q[14] -> c[2];
measure q[0] -> c[2];
```

### Expected behavior

Output with whether circuits are equivalent or not

### How to Reproduce

```
from mqt import qcec

Code:
    print("With transform_dynamic_circuit")
    result = qcec.verify("circ1.qasm", "circ2.qasm", transform_dynamic_circuit=True)
    
Terminal Output:
    With transform_dynamic_circuit
    zsh: segmentation fault  /opt/anaconda3/envs/smt_compiler/bin/python 

Code:
    print("Without transform_dynamic_circuit")
    result = qcec.verify("circ1.qasm", "circ2.qasm")

Terminal ouput:
    Without transform_dynamic_circuit
    zsh: bus error  /opt/anaconda3/envs/smt_compiler/bin/python 

```

**Comment by burgholzer** [comment]
Hey 👋🏻 

Many thanks for opening this issue and for the complete description of the problem.

I am currently on vacation and will only be able to look more deeply next week.
However, let me clarify a few things first:
In what sense would you consider these circuits equivalent? They act on different numbers of qubits (13 vs 15) and contain a different number of measurements (3 vs 6), but the same number of classical registers (3).
I am fairly sure this is what trips up QCEC, i.e. repeated measurements into a single classical bit without any action in between.
In general, I think I'd like to understand a bit more about the kind of equivalence you are looking for.

**Comment by ritu-thombre99** [comment]
I tried removing the measurements of q[13] and q[14] from circ2.qasm
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[15];
creg c[3];
cx q[3],q[2];
cx q[7],q[8];
cx q[9],q[8];
cx q[5],q[8];
cx q[5],q[2];
cx q[1],q[2];
cx q[2],q[1];
cx q[1],q[2];
cx q[4],q[5];
cx q[5],q[4];
cx q[4],q[5];
cx q[2],q[5];
cx q[8],q[9];
cx q[9],q[8];
cx q[8],q[9];
cx q[8],q[5];
cx q[3],q[11];
cx q[11],q[3];
cx q[3],q[11];
cx q[2],q[3];
cx q[3],q[2];
cx q[2],q[3];
rx(pi) q[2];
cx q[2],q[5];
cx q[2],q[1];
cx q[2],q[3];
cx q[3],q[2];
cx q[2],q[3];
cx q[3],q[11];
cx q[11],q[3];
cx q[3],q[11];
cx q[7],q[12];
cx q[12],q[7];
cx q[7],q[12];
cx q[7],q[8];
cx q[8],q[7];
cx q[7],q[8];
cx q[7],q[12];
cx q[8],q[9];
cx q[8],q[5];
cx q[5],q[8];
cx q[8],q[5];
cx q[5],q[8];
cx q[2],q[5];
cx q[5],q[2];
cx q[2],q[5];
cx q[2],q[1];
cx q[0],q[1];
cx q[1],q[0];
cx q[0],q[1];
cx q[2],q[5];
cx q[5],q[2];
cx q[2],q[5];
cx q[9],q[10];
cx q[10],q[9];
cx q[9],q[10];
cx q[8],q[9];
cx q[9],q[8];
cx q[8],q[9];
cx q[12],q[7];
cx q[7],q[12];
cx q[7],q[12];
cx q[12],q[7];
cx q[7],q[12];
measure q[10] -> c[0];
cx q[9],q[10];
cx q[10],q[9];
cx q[9],q[10];
measure q[10] -> c[1];
measure q[0] -> c[2];
```

And I get this error
``` ValueError: DD for non-unitary operation not available! ```

**Comment by ritu-thombre99** [comment]
I want them to be equivalent in terms of the quantum state at the end of all the gates

**Comment by burgholzer** [comment]
> I tried removing the measurements of q[13] and q[14] from circ2.qasm
> 
> ```
> OPENQASM 2.0;
> include "qelib1.inc";
> qreg q[15];
> creg c[3];
> cx q[3],q[2];
> cx q[7],q[8];
> cx q[9],q[8];
> cx q[5],q[8];
> cx q[5],q[2];
> cx q[1],q[2];
> cx q[2],q[1];
> cx q[1],q[2];
> cx q[4],q[5];
> cx q[5],q[4];
> cx q[4],q[5];
> cx q[2],q[5];
> cx q[8],q[9];
> cx q[9],q[8];
> cx q[8],q[9];
> cx q[8],q[5];
> cx q[3],q[11];
> cx q[11],q[3];
> cx q[3],q[11];
> cx q[2],q[3];
> cx q[3],q[2];
> cx q[2],q[3];
> rx(pi) q[2];
> cx q[2],q[5];
> cx q[2],q[1];
> cx q[2],q[3];
> cx q[3],q[2];
> cx q[2],q[3];
> cx q[3],q[11];
> cx q[11],q[3];
> cx q[3],q[11];
> cx q[7],q[12];
> cx q[12],q[7];
> cx q[7],q[12];
> cx q[7],q[8];
> cx q[8],q[7];
> cx q[7],q[8];
> cx q[7],q[12];
> cx q[8],q[9];
> cx q[8],q[5];
> cx q[5],q[8];
> cx q[8],q[5];
> cx q[5],q[8];
> cx q[2],q[5];
> cx q[5],q[2];
> cx q[2],q[5];
> cx q[2],q[1];
> cx q[0],q[1];
> cx q[1],q[0];
> cx q[0],q[1];
> cx q[2],q[5];
> cx q[5],q[2];
> cx q[2],q[5];
> cx q[9],q[10];
> cx q[10],q[9];
> cx q[9],q[10];
> cx q[8],q[9];
> cx q[9],q[8];
> cx q[8],q[9];
> cx q[12],q[7];
> cx q[7],q[12];
> cx q[7],q[12];
> cx q[12],q[7];
> cx q[7],q[12];
> measure q[10] -> c[0];
> cx q[9],q[10];
> cx q[10],q[9];
> cx q[9],q[10];
> measure q[10] -> c[1];
> measure q[0] -> c[2];
> ```
> 
> And I get this error `ValueError: DD for non-unitary operation not available!`

One of the reasons that particular example is throwing an error is because you are measuring `q[10]`, but then apply further gates on that qubit after the measurement.
You are also subsequently measuring that qubit again.
Is there any reason for not writing that circuit as

```qasm
OPENQASM 2.0;
include "qelib1.inc";
qreg q[15];
creg c[3];
cx q[3],q[2];
cx q[7],q[8];
cx q[9],q[8];
cx q[5],q[8];
cx q[5],q[2];
cx q[1],q[2];
cx q[2],q[1];
cx q[1],q[2];
cx q[4],q[5];
cx q[5],q[4];
cx q[4],q[5];
cx q[2],q[5];
cx q[8],q[9];
cx q[9],q[8];
cx q[8],q[9];
cx q[8],q[5];
cx q[3],q[11];
cx q[11],q[3];
cx q[3],q[11];
cx q[2],q[3];
cx q[3],q[2];
cx q[2],q[3];
rx(pi) q[2];
cx q[2],q[5];
cx q[2],q[1];
cx q[2],q[3];
cx q[3],q[2];
cx q[2],q[3];
cx q[3],q[11];
cx q[11],q[3];
cx q[3],q[11];
cx q[7],q[12];
cx q[12],q[7];
cx q[7],q[12];
cx q[7],q[8];
cx q[8],q[7];
cx q[7],q[8];
cx q[7],q[12];
cx q[8],q[9];
cx q[8],q[5];
cx q[5],q[8];
cx q[8],q[5];
cx q[5],q[8];
cx q[2],q[5];
cx q[5],q[2];
cx q[2],q[5];
cx q[2],q[1];
cx q[0],q[1];
cx q[1],q[0];
cx q[0],q[1];
cx q[2],q[5];
cx q[5],q[2];
cx q[2],q[5];
cx q[9],q[10];
cx q[10],q[9];
cx q[9],q[10];
cx q[8],q[9];
cx q[9],q[8];
cx q[8],q[9];
cx q[12],q[7];
cx q[7],q[12];
cx q[7],q[12];
cx q[12],q[7];
cx q[7],q[12];
measure q[10] -> c[0];
measure q[9] -> c[1];
measure q[0] -> c[2];
```

Furthermore, are you sure that the last part of the circuit as written here is as you intended it to be?
The sequence
```qasm
cx q[12],q[7];
cx q[7],q[12];
cx q[7],q[12];
cx q[12],q[7];
cx q[7],q[12];
```
at the end, simply reduces to
```qasm
cx q[7],q[12];
```

**Comment by burgholzer** [comment]
> I want them to be equivalent in terms of the quantum state at the end of all the gates Physical qubits 13 and 14 both have to be |0> at the end. I can provide the final mapping at the end to compare the circuits.

Ok, so let me try to get this straight:
- the first circuit acts on 13 qubits and measures 3 of them at the end of the circuit
- the second circuit acts on 15 qubits and also measures 3 of them at the end of the circuit
- you are not interested in the value of the three measured qubits in both circuits
- you want q[13] and q[14] in the second circuit to be zero at the end
- you want the remaining 10 qubits in both circuits to represent the same state
- in all of this, you are only interested in the resulting state when you start with the all-zero state `|0...0>`

Please correct me if anything of the above is wrong.

As of now, QCEC is not equipped for verifying that kind of equivalence out of the box.
It typically considers a much stricter notion of equivalence (unitary equivalence).
If I understood correctly, what you are looking for is "simply" a question of simulating both circuits with the all-zero state input and comparing the resulting states.
It should be possible to make this possible with QCEC, but might require some implementation work.

**Comment by ritu-thombre99** [comment]
It works with the following code bit:
```python
qcec.verify("circ1.qasm", "circ2.qasm",
                     transform_dynamic_circuit=True,
                     backpropagate_output_permutation=True,
                     fix_output_permutation_mismatch=True)
```
